blog/urls.py
"""Direct users to appropriate urls depending on needs."""
from django.urls import path
from .views import blog_list, blog_details, add_article, article_update

app_name = "blog"

urlpatterns = [
    path('articles/', blog_list, name='blog_list'),
    path('article/<int:id>/', blog_details, name='blog_detail'),
    path('article/add/', add_article, name="add_article"),
    path('article/<int:id>/edit', article_update, name="article_update"),
]

hobbysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('user_management.urls', namespace='profile')),
    path('', include('home.urls', namespace='home')),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

blog/models.py
"""Create models ArticleCategory & Article with appropriate fields."""

from django.db import models
from user_management.models import Profile


class ArticleCategory(models.Model):
    """Create ArticleCategory with appropriate field, sorted alphabetically."""

    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        """Return the name of the Article Category."""
        return self.name

    class Meta:
        """Order the article categorys alphabetically."""

        ordering = ["name"]


class Article(models.Model):
    """Create Article model with appropriate field, sorted by date."""

    title = models.CharField(max_length=255)
    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    category = models.ForeignKey(
        ArticleCategory, on_delete=models.SET_NULL, null=True)
    entry = models.TextField()
    creation_date = models.DateTimeField(auto_now_add=True)
    most_recent_update_date = models.DateTimeField(auto_now=True)
    header_image = models.ImageField(upload_to='article_headers/', null=False)

    def __str__(self):
        """Return the name of the Article itself."""
        return self.title

    class Meta:
        """Order the article based on its creation date."""

        ordering = ["-creation_date"]


class Comment(models.Model):
    """Create Comment model with appropriate field, sorted by date."""

    author = models.ForeignKey(Profile, on_delete=models.SET_NULL, null=True)
    article = models.ForeignKey(Article, on_delete=models.CASCADE)
    entry = models.TextField()
    most_recent_update_date = models.DateTimeField(auto_now=True)
    creation_date = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Order the comments based on its creation date."""

        ordering = ["creation_date"]


class ArticleImage(models.Model):
    """Create ArticleImage model with appropriate fields."""

    image = models.ImageField(upload_to='recipe_images/', null=False)
    description = models.TextField(max_length=255)
    article = models.ForeignKey(
        Article, on_delete=models.CASCADE, related_name='images')

blog/forms.py
"""Create forms with appropriate fields."""

from django import forms
from .models import Article, Comment, ArticleImage


class ArticleForm(forms.ModelForm):
    """Create a form to add details for the Article."""

    class Meta:
        """Create fields for the form and link Article model."""

        model = Article
        fields = ['title', 'category', 'entry', 'header_image']


class ArticleImageForm(forms.ModelForm):
    """Creates a form to update image for the Article."""

    class Meta:
        """Create fields for the form and link ArticleImage model."""

        model = ArticleImage
        fields = ['image', 'description']


class CommentForm(forms.ModelForm):
    """Creates a form to write a comment."""

    class Meta:
        """Create fields for the form and link Comment model."""

        model = Comment
        fields = ['entry']

blog/views.py
"""Receives web requests and returns the necessary web response."""
from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from .models import Article, ArticleCategory
from user_management.models import Profile
from .forms import ArticleForm, CommentForm


@login_required
def blog_list(request):
    """Return blog list with user-specific and categorized articles."""
    user_profile = request.user.profile
    categories = ArticleCategory.objects.all()
    user_articles = Article.objects.filter(author=user_profile)
    categorized_articles = {}
    for category in categories:
        categorized_articles[category] = Article.objects.filter(
            category=category)
    return render(request, "blog_list.html", {
        "user_articles": user_articles,
        "categorized_articles": categorized_articles
    })


def blog_details(request, id):
    """Return blog_details html file with apt context."""
    article = Article.objects.get(id=id)
    form = CommentForm()
    if request.method == "POST":
        form = CommentForm(request.POST)
        if form.is_valid():
            comment = form.save(commit=False)
            comment.article = article
            profile = Profile.objects.get(user=request.user)
            comment.author = profile
            comment.save()
            print(comment.entry)
            return redirect('blog:blog_detail', article.id)
    comments = article.comment_set.all().order_by('-creation_date')
    other_articles = Article.objects.filter(
        author=article.author).exclude(pk=article.pk)[:2]
    return render(request, 'blog_details.html', {
        'article': article,
        'comment_form': form,
        'comments': comments,
        'other_articles': other_articles,
    })


@login_required
def add_article(request):
    """Allow logged-in users to create a new article."""
    form = ArticleForm()
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES)
        if form.is_valid():
            article = form.save(commit=False)
            profile = Profile.objects.get(user=request.user)
            article.author = profile
            article.save()
            return redirect("blog:blog_list")
    return render(request, "add_article.html", {"form": form})


@login_required
def article_update(request, id):
    """Allow logged-in users to update their article."""
    article = get_object_or_404(Article, pk=id)
    if str(article.author) != str(request.user):
        return redirect("blog:blog_list")
    if request.method == "POST":
        form = ArticleForm(request.POST, request.FILES, instance=article)
        if form.is_valid():
            form.save()
            return redirect('blog:blog_detail', article.id)
    else:
        form = ArticleForm(instance=article)
    return render(request, 'add_article.html',
                  {'form': form, 'article': article})

blog/templates/add_article.html
{% extends 'base.html' %}
{% load static %}

{% block title %} 
{% block head %}
<link rel="stylesheet" href="{% static 'blog/styles/style.css' %}">
{% endblock %}


{{name}}
{% endblock %}

{% block heading %}Add Article{% endblock %}

{% block content %} 
<h1 class="UpdateArticleHeader">Blog</h1>


<section class = "UpdateArticleSection">
    <div class = "UpdateArticleContainer">
        <h1>Update/Create Article:</h1>
        <div class ="UpdateArticleForm">
            <form method="POST" enctype="multipart/form-data">
                {% csrf_token %}
                {{form}}
                <button type="submit", value="submit">submit</button>
            </form>
        </div>
    </div>
</section>
    
{% endblock %}

blog/templates/blog_details.html
{% extends "base.html" %}
{% load static %}

{% block title %}{{ article.title }}{% endblock %}
{% block head %}
<link rel="stylesheet" href="{% static 'blog/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="BlogDetailsArticleTitle">Blog</h1>

<section class = "BlogDetailsArticleSection">
    <div class = "BlogDetailsArticleContainer">
        <h1 class="BlogDetailsArticleTitleInner">{{article.title}}</h1>
        <p class ="BlogDetailsArticleDate"> This article was written on: {{article.creation_date}} </p>
        <p class ="BlogDetailsArticleAuthor">Written by: {{article.author}}</p>
        {% if article.author.display_name == user.profile.display_name %}
        <p class="BlogDetailsArticleUpdate"><a href ="{% url 'blog:article_update' id=article.id %} ">Article Update</a></p>
        {% endif %}
        <hr>
        <div class ="BlogDetailsHeaderImage"><img src ="{{article.header_image.url }}"></div>
        <div class = "BlogDetailsArticleEntry">{{article.entry}}</div>
    </div>
</section>

<section class = "BlogDetailsCommentSection">
    <div class = "BlogDetailsAddCommentContainer">
        <h1 class = "BlogDetailsAddCommentTitle">Add a comment...</h1>
        <div class = "BlogDetailsAddCommentForm">
                <form method="post" action="{% url 'blog:blog_detail' article.id %}">
                {% csrf_token %}
                {{ comment_form.as_p }}
            <button type="submit">Post Comment</button>
            </form>
        </div>
            <hr>
        <div class="BlogDetailsAllCommentsContainer">
            <h1 class = "BlogDetailsAllCommentsTitle">Comments:</h1>
            {% for comment in comments %}
            <div>
                <p><strong>{{ comment.author.user.username }}:</strong> {{ comment.entry }}</p>
                <p><em>{{ comment.creation_date }}</em></p>
            </div>
            {% empty %}
                <p>No comments yet.</p>
            {% endfor %}
        </div>
    </div>
   
</section>

<section class = "BlogDetailsOtherArticleSection">
    <div class = "BlogDetailsOtherArticlesContainer">
        <h1 class = "BlogDetailsOtherArticlesHeader">You may be interested in {{article.author}}'s other works. </h1>
        <hr>
        <div class = "InnerBlogDetailsOtherArticlesContainer">
            {% for other_article in other_articles %}
            <div class = "OtherArticleDate"> Written on {{other_article.creation_date}} </div>
            <div class  = "OtherArticleTitle"><a href="{% url 'blog:blog_detail' other_article.id %}">{{other_article.title }}</a></div>
             {% empty %}
            <div class = "NoOtherArticles">No other articles by this author.</div>
                {% endfor %}
        </div>
    </div>
    <div class="ArticleListButtonContainer">
        <a href="{% url 'blog:blog_list' %}">
            <button class="addButton">Go Back to Article List</button>
        </a>
    </div>
</section>

{% endblock %}

blog/templates/blog_list.html
{% extends "base.html" %}
{% load static %}
{% block title %}Blog - Hobby Site{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'blog/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="BlogTitle">Blog</h1>

{% if user.is_authenticated %}

<section class="UserArticlesSection">
  <div class="UserArticlesContainer">
    <h2 class="UserArticlesHeader">Your Articles:</h2>
    <div class="InnerUserContainer">
        {% for article in user_articles %}
          <div class="Date"> Written on: {{ article.creation_date }}</div>
          <div class="Category">Category: {{ article.category.name }}</div>
          <div class="Title"><a href="{% url 'blog:blog_detail' article.id %}">{{ article.title }}</a></div>
      {% empty %}      
      <div class = "NoOtherArticles">You haven't written any articles yet.</div>
      {% endfor %}
</section>

{% endif %}

</div>

<section class ="AllArticlesSection">
  <div class="AllArticlesContainer">
    <h1 class="AllArticlesHeader">All Articles by Category:</h1>
    <div class="InnerAllClassContainer">
      {% for category, articles in categorized_articles.items %}
      <div class = "OtherArticleCategory">Category: {{category.name}} </div>
      <div class = "Description">{{category.description}} </div>
      <div></div>
      {% if articles %}
      {% for article in articles %}
      {% if article.author.display_name != user.profile.display_name %}
      <div class = "Author"> Written by {{article.author}} </div>
      <div class = "OtherArticleDate"> Written on {{article.creation_date}} </div>
      <div class  = "OtherArticleTitle"><a href="{% url 'blog:blog_detail' article.id %}">{{ article.title }}</a></div>
            {% endif%}
                  
           {% endfor %}    
      {% else %}
      <div class = "NoOtherArticles">No articles in this category yet.</div>
      {% endif %}
       {% empty %}      
      <div class = "NoOtherArticles">No articles have been written yet.</div>
      {% endfor %}    

</section>

{% if user.is_authenticated %}
<div class="ArticleListButtonContainer">
        <a href="{% url 'blog:add_article' %}">
            <button class="addButton">Create Article</button>
        </a>
{% endif %}

{% endblock %}