blog/urls.py
"""Direct users to appropriate urls depending on needs."""
from django.urls import path
from .views import blog_list, blog_details, add_article, article_update

app_name = "blog"

urlpatterns = [
    path('articles/', blog_list, name='blog_list'),
    path('article/<int:id>/', blog_details, name='blog_detail'),
    path('article/add/', add_article, name="add_article"),
    path('article/<int:id>/edit', article_update, name="article_update"),
]

commissions/urls.py
"""Direct users to appropriate urls depending on needs."""

from django.urls import path
from .views import CommissionListView, commission_detail, create_commission, edit_commission

urlpatterns = [

    path('list', CommissionListView.as_view(), name='commissions-list'),
    path('detail/<int:pk>', commission_detail, name='commission-detail'),
    path('add', create_commission, name='commissions-create'),
    path('<int:pk>/edit', edit_commission, name='commission-edit'),

]

app_name = 'commissions'

hobbysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('user_management.urls', namespace='profile')),
    path('', include('home.urls', namespace='home')),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

commissions/models.py
"""Create models Commission and Comments with appropriate fields."""

from django.db import models
from django.urls import reverse

from user_management.models import Profile


class Commission(models.Model):
    """Create Commission with appropriate field, sorted by time created sorted ascendingly."""

    title = models.CharField(max_length=255)
    author = models.ForeignKey(Profile, on_delete=models.CASCADE, null=True)
    description = models.TextField()
    STATUS_CHOICES = [
        ('a_open', 'Open'),
        ('b_full', 'Full'),
        ('c_completed', 'Completed'),
        ('d_discontinued', 'Discontinued'),
    ]
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='a_open')
    created_on = models.DateTimeField(auto_now_add=True)
    updated_on = models.DateTimeField(auto_now=True)

    def __str__(self):
        """Return the title of the Commission."""

        return self.title

    def get_absolute_url(self):
        """Return the url of the Commission."""

        return reverse('commissions:commission-detail', args=[self.pk])

    def get_status(self, status):
        """"return status of the Commission."""
        return status

    class Meta:
        """Orders Commission by time created ascendingly."""

        ordering = ["created_on"]


class Job(models.Model):
    """Create Jobs with appropriate field, sorted by status (Open > Full), manpower 
    required, in descending order, then role, in ascending order"""
    commission = models.ForeignKey(
        Commission,
        on_delete=models.CASCADE,
    )
    role = models.CharField(max_length=255)
    manpower_required = models.PositiveBigIntegerField()
    STATUS_CHOICES = [
        ('a_open', 'Open'),
        ('b_full', 'Full'),
    ]
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='a_open')

    def __str__(self):
        """Return the role of the Job."""
        return self.role

    def get_commission(self):
        return self.commission

    class Meta:
        """Orders Jobs by status (Open > Full), manpower required, 
        in descending order, then role, in ascending order"""

        ordering = ["status", "-manpower_required", "role"]


class JobApplication(models.Model):
    job = models.ForeignKey(Job, on_delete=models.CASCADE,)
    applicant = models.ForeignKey(Profile, on_delete=models.CASCADE,)
    STATUS_CHOICES = [
        ('a_pending', 'Pending'),
        ('b_accepted', 'Accepted'),
        ('c_rejected', 'Rejected'),
    ]
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='a_pending')

    applied_on = models.DateTimeField(auto_now_add=True)

    class Meta:
        """Orders Jobs by status (Open > Full), manpower required, 
        in descending order, then role, in ascending order"""

        ordering = ["status", "-applied_on"]

commissions/forms.py
from django import forms
from django.contrib.auth.models import User

from .models import Commission, Job, JobApplication


class CommissionCreateForm(forms.ModelForm):
    """Create a form to Create a Commission."""

    class Meta:
        model = Commission
        fields = ['title', 'description', 'status']


class JobApplicationForm(forms.ModelForm):
    """Create a form to apply for a Job."""

    class Meta:
        model = JobApplication
        exclude = ['job', 'applicant', 'status',]


class CommissionEditForm(forms.ModelForm):
    """Create a form to edit a Commission."""

    class Meta:
        model = Commission
        fields = ['title', 'description', 'status']


class JobCreateForm(forms.ModelForm):
    """Create a form to create a Job."""

    class Meta:
        model = Job
        fields = ['role', 'manpower_required']

commissions/views.py
"""Receives web requests and returns the necessary web response."""

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required
from django.views.generic.list import ListView
from django.urls import reverse

from .models import Commission, Job, JobApplication
from .forms import CommissionCreateForm, JobApplicationForm, CommissionEditForm, JobCreateForm


class CommissionListView(ListView):
    """Return commission_list html file with apt context."""
    model = Commission
    template_name = "commission_list.html"
    ordering = ["status", "-created_on"]

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        commissions = Commission.objects.all()
        jobs = Job.objects.all()
        applications = JobApplication.objects.all()
        context["commissions"] = commissions
        context["jobs"] = jobs
        context["applications"] = applications
        return context


def commission_detail(request, pk):
    """Return commission_detail html file with apt context."""

    commission = get_object_or_404(Commission, pk=pk)
    job_application = 0

    if request.method == 'POST':
        form = JobApplicationForm(request.POST)
        if form.is_valid():
            job_application = form.save(commit=False)
            job_id = request.POST.get("job_id")
            job_application.job = get_object_or_404(Job, id=job_id)
            job_application.applicant = request.user.profile
            job_application.save()
            return redirect('/commissions/detail/' + str(commission.pk))
    jobs = Job.objects.filter(commission=commission)
    applicants = JobApplication.objects.filter(job__in=jobs)
    people_required = 0
    for job in jobs:
        people_required += job.manpower_required
    accepted = 0
    applicant_number = 0
    for applicant in applicants:
        applicant_number += 1
        if applicant.status == 'b_accepted':
            accepted += 1
    open_slots = people_required - accepted
    ctx = {
        "commission": commission,
        "jobs": jobs,
        "people_required": people_required,
        "open_slots": open_slots,
        "applicants": applicants,
        "applicant_number": applicant_number
    }
    return render(request, "commission_detail.html", ctx)


@login_required
def create_commission(request):
    """Return commission_create html file with apt context."""
    commission_form = CommissionCreateForm()
    job_form1 = JobCreateForm()
    if request.method == 'POST':
        commission_form = CommissionCreateForm(request.POST)
        job_form1 = JobCreateForm(request.POST or None)
        if all([commission_form.is_valid(), job_form1.is_valid()]):
            commission = commission_form.save(commit=False)
            commission.author = request.user.profile
            commission.save()
            job1 = job_form1.save(commit=False)
            job1.commission = commission
            job1.save()
            return redirect('/commissions/list', pk=commission.pk)
    ctx = {
        "commission_form": commission_form,
        "job_form1": job_form1,
    }
    return render(request, 'commission_create.html', ctx)


@login_required
def edit_commission(request, pk):
    """Return commission_edit html file with apt context."""
    commission = get_object_or_404(Commission, pk=pk)
    commission_form = CommissionEditForm(instance=commission)
    jobs = Job.objects.filter(commission=commission)
    applicants = JobApplication.objects.filter(job__in=jobs)
    people_required = 0
    for job in jobs:
        people_required += job.manpower_required
    accepted = 0
    for applicant in applicants:
        if applicant.status == 'b_accepted':
            accepted += 1
    open_slots = people_required - accepted
    if accepted >= people_required:
        commission.status = 'b_full'
        commission.save()
    ctx = {
        "commission_form": commission_form,
        "commission": commission,
        "jobs": jobs,
        "people_required": people_required,
        "open_slots": open_slots,
        "applicants": applicants
    }
    if request.method == 'POST':
        commission_form = CommissionEditForm(request.POST, instance=commission)
        if commission_form.is_valid():
            commission = commission_form.save(commit=False)
            commission.author = request.user.profile
            if open_slots < 1:
                commission.status = 'b_full'
            commission.save()
        return render(request, "commission_detail.html", ctx)

    ctx = {"commission_form": commission_form, "commission": commission}
    return render(request, "commission_edit.html", ctx)

commissions/templates/commission_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Commissions - Hobbysite {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'commissions/styles/style.css' %}">
{% endblock %}

{% block content %}
    <h1 class="app-header">COMMISSIONS</h1> <br>
    <div class = main-content>
        <h2 class="com-header">Create a New Commission</h2>
        <div class="coms">
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <h2>Commission Details: </h2>
            {{ commission_form.as_p }}
            <h2>Job Details: </h2>
            {{job_form1.as_p}} <br>
            <button type="submit" value="submit">Submit</button>
        </form>
    </div>
{% endblock %}

commissions/templates/commission_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Commissions - Hobbysite {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'commissions/styles/style.css' %}">
{% endblock %}

{% block content %}
    <h1 class="app-header">COMMISSIONS</h1> <br>
    <div class = main-content>
        <h2>Commission Details</h2>
            <h3><a href="{% url 'commissions:commissions-list' %}">Back to Commission List</a></h3>
            <h2 class="com-header">TITLE: {{commission.title}}</h2>
            <div class="coms">
                <div class="detail-entry">
                <p>AUTHOR: {{commission.author}}</p>
                <p>Status: {{commission.get_status_display}}</p>
                {% if user.profile == commission.author %}
                    <a href="{% url 'commissions:commission-edit' commission.pk %}">Edit Commission</a>
                {% endif %}
                </div>
            <div class="detail-entry">
                <p>JOBS:
                    {% for job in jobs %}
                        <br> <li>{{job.role}}</li>
                        <br> 
                        {% if user.is_authenticated %}
                            <form method="POST" enctype="multipart/form-data">
                                {% csrf_token %}
                                <input type="hidden" name="job_id" value="{{ job.id }}"/>
                                {{ form }}
                                {% if open_slots < 1 %}
                                    <button disabled type="submit" value="Apply to Job">Apply to Job</button>
                                {% elif user.profile == commission.author %}
                                    <p>Current Number of Applicants: {{applicant_number}}</p> 
                                {% else %}
                                    <button type="submit" value="Apply to Job">Apply to Job</button>
                                {% endif %}
                            </form>
                        {% endif %}
                    {% endfor %}
                </p>
            </div>
            <div class="detail-entry">
                <p>DESCRIPTION: <br> {{commission.description}}</p>
            </div>
            <div class="detail-entry">
                <p>People required: {{people_required}}</p>
                <p>Open Slots: {{open_slots}}</p>
            </div>
            <div class="detail-entry">
                <p>Created on: <br> {{commission.created_on}}</p>
                <p>Updated on: <br> {{commission.updated_on}}</p>
            </div>
        </div>
    </div>
{% endblock %}

commissions/templates/commission_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Commissions - Hobbysite {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'commissions/styles/style.css' %}">
{% endblock %}

{% block content %}
    <h1 class="app-header">COMMISSIONS</h1> <br>
    <div class = main-content>
        <h2 class="com-header">Update the Commission</h2>
        <div class="coms">
            <p><strong>Logged in user:</strong> {{ user.username }}</p>
            Title: {{commission.title}} <br>
            Author: {{commission.author}} <br>
            Created on: {{commission.created_on}} <br>
            Status: {{commission.get_status_display}} <br>
            Description: {{commission.description}} <br>
            <form method="POST">
                {% csrf_token %}
                {{ commission_form.as_p }}
                <button type="submit">Update Commission</button>
            </form>
        </div>
    </div>
{% endblock %}

commissions/templates/commission_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Commissions - Hobbysite {% endblock %}

{% block head %}
    <link rel="stylesheet" href="{% static 'commissions/styles/style.css' %}">
{% endblock %}

{% block content %}
    <h1 class="app-header">COMMISSIONS</h1> <br>
    <div class = main-content>
        <h2>Complete List</h2>
        <h3><a href="/commissions/add">Create Commission</a></h3>
        {% if user.is_authenticated %}
            <h2 class="com-header">Created Commissions</h2>
            <div class="coms">
                <ul>
                    {% for commission in object_list %}
                        {% if user.profile ==  commission.author%} 
                            <div class="entry">
                                <h3><a href="{{commission.get_absolute_url}}">{{commission.title}}</a></h3>
                                <li>Created on: {{commission.created_on}}</li>  
                                <li>Status: {{commission.get_status_display}}</li>   
                                <br>
                            </div>
                        {% endif %}
                    {% endfor %} 
                </ul>
            </div>
            <h2 class="com-header">Applied Commissions</h2>
            <div class="coms">
                <ul>
                    {% for app in applications %}
                    {% if app.applicant == user.profile%}
                        {% for job in jobs %}
                        {% if app.job == job %}
                            {% for com in commissions %}
                            {% if job.commission == com %}
                                <div class ="entry">
                                <h3><a href="{{com.get_absolute_url}}">{{com.title}} ({{job.role}})</a></h3>
                                <li>Applied on: {{app.applied_on}}</li>   
                                <li>Status: {{com.get_status_display}}</li>                         
                                <br>
                                </div>
                            {% endif %}
                            {% endfor %}
                        {% endif %}
                        {% endfor %}
                    {% endif %}
                    {% endfor %}
                </ul>
            </div>
        {% endif %}
        <h2 class="com-header">All Commissions</h2>
        <div class="coms">
            <ul>
                {% for commission in object_list %}
                    <div class ="entry">
                        <h3><a href="{{commission.get_absolute_url}}">{{commission.title}}</a></h3>
                        <li>Created on: {{commission.created_on}}</li>
                        <li>Status: {{commission.get_status_display}}</li>                
                        <br>
                    </div>
                {% endfor %}
            </ul>
        </div>
    </div>
{% endblock %}