blog/urls.py
"""Direct users to appropriate urls depending on needs."""
from django.urls import path
from .views import blog_list, blog_details, add_article, article_update

app_name = "blog"

urlpatterns = [
    path('articles/', blog_list, name='blog_list'),
    path('article/<int:id>/', blog_details, name='blog_detail'),
    path('article/add/', add_article, name="add_article"),
    path('article/<int:id>/edit', article_update, name="article_update"),
]

commissions/urls.py
"""Direct users to appropriate urls depending on needs."""

from django.urls import path
from .views import CommissionListView, commission_detail, create_commission, edit_commission

urlpatterns = [

    path('list', CommissionListView.as_view(), name='commissions-list'),
    path('detail/<int:pk>', commission_detail, name='commission-detail'),
    path('add', create_commission, name='commissions-create'),
    path('<int:pk>/edit', edit_commission, name='commission-edit'),

]

app_name = 'commissions'

hobbysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('user_management.urls', namespace='profile')),
    path('', include('home.urls', namespace='home')),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchstore/urls.py
"""Direct users to appropriate urls depending on needs."""

from django.urls import path
from .views import product_list, product_detail, create_product
from .views import cart_list, edit_product, transactions_list, edit_cart_item

urlpatterns = [

    path('items', product_list, name='product-list'),
    path('item/<int:pk>', product_detail, name='product-detail'),
    path('item/add', create_product, name='product-create'),
    path('item/<int:pk>/edit', edit_product, name='product-edit'),
    path('cart', cart_list, name='cart-list'),
    path('transactions', transactions_list, name='transactions'),
    path('cart/item/<int:pk>/edit', edit_cart_item, name='cart-item-edit'),

]

app_name = 'merchstore'

user_management/urls.py
from django.urls import path

from .views import profile_update
app_name = "user_management"

urlpatterns = [
    path('<str:username>/', profile_update, name='profile-update'),

]

wiki/urls.py
# ledger/urls.py
"""Defines namespace (wiki) and matches views to corresponding URLs."""

from django.urls import path

from .views import ArticleListView, ArticleDetailView, ArticleCreateView, ArticleUpdateView, CommentUpdateView


app_name = 'wiki'


urlpatterns = [
    path('articles/', ArticleListView.as_view(), name="article_list"),
    path('article/<int:pk>/', ArticleDetailView.as_view(), name="article_details"),
    path('article/add/', ArticleCreateView.as_view(), name="article_create"),
    path('article/<int:pk>/edit/', ArticleUpdateView.as_view(), name="article_update"),
    path('comment/<int:pk>/edit/', CommentUpdateView.as_view(), name="comment_edit")
]

templates/base.html
{% load static %}
<!DOCTYPE html>
<html lang="en">
<html>
    <head>
        <meta charset="UTF-8"/>
        <meta name="viewport" content="width=device-width, initial-scale = 1" />
        <title>{% block title %}Hobby Site{% endblock %}</title>
        <link rel="stylesheet" href="{% static 'styles/base.css' %}">
        {% block head %}
        {% endblock %}
    </head>


    <body>
         <header class="header">
        <a href="/" class="name">Hobby Site</a>
        <nav class = "navbar">
            <a href="{% url 'blog:blog_list'%}">Blog</a>
            <a href="{% url 'commissions:commissions-list'%}">Commissions</a>
            <a href="{% url 'merchstore:product-list'%}">Merchstore</a>
            <a href="{% url 'wiki:article_list'%}">Wiki</a>
         {% if user.is_authenticated %}
            <a href="{% url 'user_management:profile-update' request.user.username %}">Profile</a>
            <form method="post" action="{% url 'logout' %}" style="display: inline;">
                {% csrf_token %}
                <button type="submit" class="btn">Log out</button>
            </form>
        {% else %}
            <a href="{% url 'login' %}">Log in</a>
        {% endif %}
        </nav>
    </header>

        {% block content %}
        {% endblock %}
    </body>
</html>