blog/urls.py
"""Direct users to appropriate urls depending on needs."""
from django.urls import path
from .views import blog_list, blog_details, add_article, article_update

app_name = "blog"

urlpatterns = [
    path('articles/', blog_list, name='blog_list'),
    path('article/<int:id>/', blog_details, name='blog_detail'),
    path('article/add/', add_article, name="add_article"),
    path('article/<int:id>/edit', article_update, name="article_update"),
]

hobbysite/urls.py
from django.contrib import admin
from django.conf import settings
from django.conf.urls.static import static
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static


urlpatterns = [
    path('admin/', admin.site.urls),
    path('wiki/', include('wiki.urls', namespace='wiki')),
    path('blog/', include('blog.urls', namespace='blog')),
    path('commissions/', include('commissions.urls', namespace='commissions')),
    path('merchstore/', include('merchstore.urls', namespace='merchstore')),
    path('forum/', include('forum.urls', namespace='forum')),
    path('accounts/',include('accounts.urls', namespace='accounts')),
    path('accounts/', include('django.contrib.auth.urls')),
    path('profile/', include('user_management.urls', namespace='profile')),
    path('', include('home.urls', namespace='home')),
   
]
urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

merchstore/urls.py
"""Direct users to appropriate urls depending on needs."""

from django.urls import path
from .views import product_list, product_detail, create_product
from .views import cart_list, edit_product, transactions_list, edit_cart_item

urlpatterns = [

    path('items', product_list, name='product-list'),
    path('item/<int:pk>', product_detail, name='product-detail'),
    path('item/add', create_product, name='product-create'),
    path('item/<int:pk>/edit', edit_product, name='product-edit'),
    path('cart', cart_list, name='cart-list'),
    path('transactions', transactions_list, name='transactions'),
    path('cart/item/<int:pk>/edit', edit_cart_item, name='cart-item-edit'),

]

app_name = 'merchstore'

merchstore/models.py
"""Create models ProductType and Product with appropriate fields."""

from django.db import models
from django.urls import reverse

from user_management.models import Profile


class ProductType(models.Model):
    """Create ProductType with appropriate field, sorted alphabetically."""

    name = models.CharField(max_length=255)
    description = models.TextField()

    def __str__(self):
        """Return the name of the Product Type."""
        return self.name

    class Meta:
        """Order the product types alphabetically."""

        ordering = ["name"]


class Product(models.Model):
    """Create Product model with appropriate field, sorted alphabetically."""

    name = models.CharField(max_length=255)
    product_type = models.ForeignKey(
        ProductType,
        on_delete=models.SET_NULL,
        null=True,
    )
    owner = models.ForeignKey(
        Profile,
        on_delete=models.CASCADE
    )
    description = models.TextField()
    price = models.DecimalField(max_digits=20, decimal_places=2)
    stock = models.PositiveIntegerField(default=0)

    STATUS_CHOICES = [
        ('available', 'Available'),
        ('on_sale', 'On sale'),
        ('out_of_stock', 'Out of stock'),
    ]
    status = models.CharField(
        max_length=20, choices=STATUS_CHOICES, default='available')

    image = models.ImageField(upload_to='images/', null=True)

    def __str__(self):
        """Return the name of the Product."""
        return self.name

    def get_absolute_url(self):
        """Return the url of the Product."""
        return reverse('merchstore:product-detail', args=[self.pk])

    class Meta:
        """Order the products by name."""

        ordering = ["name"]


class Transaction(models.Model):
    """Create Transaction Model with appropriate fields."""

    buyer = models.ForeignKey(
        Profile,
        on_delete=models.SET_NULL,
        null=True
    )
    product = models.ForeignKey(
        Product,
        on_delete=models.SET_NULL,
        null=True
    )
    amount = models.PositiveIntegerField(default=0)

    STATUS_CHOICES = [
        ('on_cart', 'On Cart'),
        ('to_pay', 'To Pay'),
        ('to_ship', 'To Ship'),
        ('to_receive', 'To Receive'),
        ('delivered', 'Delivered'),
    ]
    status = models.CharField(max_length=20, choices=STATUS_CHOICES)
    created_on = models.DateTimeField(auto_now_add=True)

merchstore/forms.py
"""Create forms with appropriate fields."""

from django import forms
from django.contrib.auth.models import User

from .models import Product, Transaction

class ProductCreateForm(forms.ModelForm):
    """Create a form to Create a Product"""

    class Meta:
        """Create fields for the form and link Product model."""

        model = Product
        fields = ['name','product_type','description','price','stock','status','image']

class RegisterForm(forms.ModelForm):
    """Create a form to register"""

    class Meta:
        """Create fields for the form and link User model."""

        model = User
        fields = ['password','username','email']

class TransactionForm(forms.ModelForm):
    """Create a form for Transactions"""

    class Meta:
        """Create field for the form and link Transaction model."""

        model = Transaction
        fields = ['amount']

class ProductEditForm(forms.ModelForm):
    """Create a form to edit products"""

    class Meta:
        """Create field for the form and link Transaction model."""

        model = Product
        fields = ['name','product_type','description','price','stock','image']

merchstore/views.py
"""Receives web requests and returns the necessary web response."""

from django.shortcuts import render, get_object_or_404, redirect
from django.contrib.auth.decorators import login_required

from .models import Product, Transaction, ProductType
from .forms import ProductCreateForm, TransactionForm, ProductEditForm

from user_management.models import Profile


def product_list(request):
    """Return product_list html file with apt context."""
    products = Product.objects.all()

    user_products = Product.objects.none()
    other_products = products

    if request.user.is_authenticated:
        user_profile = request.user.profile
        user_products = Product.objects.filter(owner=user_profile)
        other_products = Product.objects.exclude(owner=user_profile)

        user_product_types = ProductType.objects.filter(
            product__in=user_products
        ).distinct()
        other_product_types = ProductType.objects.filter(
            product__in=other_products
        ).distinct()
    else:
        user_product_types = ProductType.objects.none()
        other_product_types = ProductType.objects.filter(
            product__in=other_products).distinct()

    ctx = {
        "products": products,
        "user_product_types": user_product_types,
        "other_product_types": other_product_types,
        "user_products": user_products,
        "other_products": other_products
    }

    return render(request, "product_list.html", ctx)


@login_required
def cart_list(request):
    """Return cart_list html file with apt context."""

    items_on_cart = Transaction.objects.filter(
        buyer=request.user.profile,
        status='on_cart'
    )

    seller_ids = items_on_cart.values_list(
        'product__owner__id', flat=True).distinct()

    sellers = Profile.objects.filter(id__in=seller_ids)

    total_price = sum(
        item.amount * item.product.price for item in items_on_cart)

    ctx = {
        "items_on_cart": items_on_cart,
        "sellers": sellers,
        "total_price": total_price,
    }
    return render(request, "cart_list.html", ctx)


def product_detail(request, pk):
    """Return product_detail html file with apt context."""
    product = get_object_or_404(Product, pk=pk)
    form = TransactionForm()
    if request.method == 'POST':
        if not request.user.is_authenticated:
            return redirect('login')
        form = TransactionForm(request.POST)

    if form.is_valid():
        transaction = form.save(commit=False)
        if transaction.amount > product.stock:
            return render(request, 'product_detail.html', {
                'form': form,
                'product': product,
                'error_message': (
                    f"Cannot add more than {product.stock} item(s) to the cart."
                ),
            })
        elif transaction.amount == 0:
            return render(request, 'product_detail.html', {
                'form': form,
                'product': product,
                'error_message': f"Cannot add 0 items to the cart."
            })

        transaction.buyer = request.user.profile
        transaction.product = product
        transaction.status = 'on_cart'
        transaction.save()

        product.stock -= transaction.amount
        if product.stock == 0:
            product.status = 'out_of_stock'
        product.save()

        return redirect('merchstore:cart-list')

    ctx = {
        'form': form,
        'product': product
    }
    return render(request, 'product_detail.html', ctx)


@login_required
def create_product(request):
    """Return product_create html file with apt context."""
    form = ProductCreateForm()
    if request.method == 'POST':
        form = ProductCreateForm(request.POST, request.FILES)
    if form.is_valid():
        product = form.save(commit=False)
        product.owner = request.user.profile
        product.save()
        return redirect('merchstore:product-detail', pk=product.pk)
    ctx = {"form": form}
    return render(request, 'product_create.html', ctx)


@login_required
def edit_product(request, pk):
    """Return product_create html file with apt context."""
    product = get_object_or_404(Product, pk=pk)
    form = ProductEditForm()
    if request.method == 'POST':
        form = ProductEditForm(request.POST, request.FILES, instance=product, )
        if form.is_valid():
            updated_product = form.save(commit=False)
            if updated_product.owner != request.user.profile:
                return render(request, 'product_detail.html', {
                    'form': form,
                    'product': product,
                    'error_message': (
                        "You are not authorized to edit this product."
                    ),
                })
            updated_product.status = 'out_of_stock' if updated_product.stock == 0 else 'available'
            updated_product.save()
            return redirect('merchstore:product-detail', pk=product.pk)
    else:
        form = ProductEditForm(instance=product)

    ctx = {"form": form, "product": product}
    return render(request, 'product_create.html', ctx)


@login_required
def transactions_list(request):
    transactions_sold = Transaction.objects.filter(
        product__owner=request.user.profile,
        status='on_cart'
    )

    buyer_ids = transactions_sold.values_list(
        'buyer__id', flat=True).distinct()
    buyers = Profile.objects.filter(id__in=buyer_ids)
    projected_earnings = sum(
        item.amount * item.product.price for item in transactions_sold)

    ctx = {
        "transactions_sold": transactions_sold,
        "buyers": buyers,
        "projected_earnings": projected_earnings,
    }

    return render(request, "transaction_list.html", ctx)


@login_required
def edit_cart_item(request, pk):
    """Return cart_edit html file with apt context."""
    transaction = get_object_or_404(
        Transaction, pk=pk, buyer=request.user.profile, status='on_cart')
    product = transaction.product
    old_amount = transaction.amount
    old_stock = product.stock
    total_product = old_amount + old_stock
    if request.method == 'POST':
        form = TransactionForm(request.POST, instance=transaction)
        if form.is_valid():
            new_transaction = form.save(commit=False)

            if new_transaction.amount > total_product:
                return render(request, 'cart_list.html', get_cart_context(request.user,
                                                                          f"Cannot add more than {total_product} item(s)."))
            elif new_transaction.amount == 0:
                product.stock += old_amount
                product.save()
                transaction.delete()
                return redirect('merchstore:cart-list')

            product.stock += old_amount - new_transaction.amount

            if product.stock == 0:
                product.status = 'out_of_stock'
            else:
                product.status = 'available'

            product.save()

            new_transaction.save()
            return redirect('merchstore:cart-list')
    else:
        form = TransactionForm(instance=transaction)

    return render(request, 'cart_edit.html', {'form': form,
                                              'transaction': transaction, 'product': product})


def get_cart_context(user, error_message=None):
    """Return cart context."""
    items_on_cart = Transaction.objects.filter(
        buyer=user.profile, status='on_cart')
    sellers = set(item.product.owner for item in items_on_cart)
    ctx = {'items_on_cart': items_on_cart, 'sellers': sellers}
    if error_message:
        ctx['error_message'] = error_message
    return ctx

merchstore/templates/cart_edit.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Edit Cart Item
{% endblock %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'merchstore/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">MERCHSTORE</h1>
<h2 class="error-message">{{ error_message }}</h2>

<div class="user-product">
    <a href="{% url 'merchstore:cart-list' %}" class="btn">View Cart</a>
    <a href="{% url 'merchstore:product-list' %}" class="btn">View Items</a>
    <a href="{% url 'merchstore:transactions' %}" class="btn">View Transactions</a>
</div>

<div class="main-content">

    <div class="section-title">Edit Product</div>
    <p class="product-generic">Product: {{ product.name }}</p>
    <p class="product-generic">Current Quantity: {{ transaction.amount }}</p>

    <form method="POST">
        {% csrf_token %}
        {{ form.as_p }}
        <button type="submit">Update Cart</button>
    </form>

</div>

{% endblock %}

merchstore/templates/cart_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
View Cart
{% endblock %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'merchstore/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">MERCHSTORE</h1>
<h2 class="error-message">{{ error_message }}</h2>

<div class="user-product">
    <a href="{% url 'merchstore:cart-list' %}" class="btn">View Cart</a>
    <a href="{% url 'merchstore:product-list' %}" class="btn">View Items</a>
    <a href="{% url 'merchstore:transactions' %}" class="btn">View Transactions</a>
</div>

<div class="main-content">
    <h2 class="section-title">Items in Cart:</h2>
    <p class="product-generic">Total Price: ₱{{total_price}}</p>

    {% for seller in sellers %}
    <h3 class="product-type-title">Seller: {{seller.display_name}}</h3>
    <div class="product-list">
        {% for item in items_on_cart %}
        {% if item.product.owner == seller %}
        <div class="product-item">
            {% if item.product.image %}
            <img src="{{ item.product.image.url }}" alt="" class="product-image">
            {% endif %}
            <div class="product-text">
                <div class="product-name">{{item.product.name}}</div>
                <div class="product-price">₱{{item.product.price}}</div>
                <div class="product-generic">QTY: {{item.amount}}</div>
            </div>
            <a href="{% url 'merchstore:cart-item-edit' pk=item.pk %}" class="btn">Edit</a>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock %}

merchstore/templates/list.html
{% extends 'base.html' %}
{% load static %}

{% block title %} Product List {% endblock %}

{% block content %}
    <ul>
        {% for product in object_list %}
        <li>Link: <a href ="{{product.get_absolute_url}}">{{product}}</a></li>
        {% endfor %}
    </ul>
{% endblock %}

merchstore/templates/product_create.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Create Product
{% endblock %}

{% block head %}
<link rel="stylesheet" href="{% static 'merchstore/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">MERCHSTORE</h1>
<h2 class="error-message">{{ error_message }}</h2>

<div class="user-product">
    <a href="{% url 'merchstore:cart-list' %}" class="btn">View Cart</a>
    <a href="{% url 'merchstore:product-list' %}" class="btn">View Items</a>
    <a href="{% url 'merchstore:transactions' %}" class="btn">View Transactions</a>
</div>

<div class="main-content">
    <h2 class="section-title">Create Product: </h2>
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        <button type="submit" value="submit" class="btn">Submit</button>
    </form>
</div>

{% endblock %}

merchstore/templates/product_detail.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Product Detail
{% endblock %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'merchstore/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">MERCHSTORE</h1>
<h2 class="error-message">{{ error_message }}</h2>

<div class="user-product">
    <a href="{% url 'merchstore:cart-list' %}" class="btn">View Cart</a>
    <a href="{% url 'merchstore:product-list' %}" class="btn">View Items</a>
    <a href="{% url 'merchstore:transactions' %}" class="btn">View Transactions</a>
</div>

<div class="main-content">
    <h2 class="section-title">Product Details</h2>

    <div class="product-detail">
        {% if product.image %}
        <img src="{{ product.image.url }}" alt="" class="product-image">
        {% endif %}

        <div class="product-text">
            <div class="product-type-title">{{product.name}}</div>
            <div class="product-price">Price: ₱{{ product.price }}</div>
            <div class="product-generic">Product type: {{ product.product_type }}</div>
            <div class="product-generic">Stock: {{ product.stock }}</div>
            <div class="product-generic">Status: {{ product.get_status_display }}</div>
            <br><br>
            <div class="product-type-title">Description:</div>
            <p>{{product.description}}</p>
        </div>
    </div>



    {% if user.profile != product.owner %}
    <form method="POST" enctype="multipart/form-data">
        {% csrf_token %}
        {{ form }}
        {% if product.stock == 0 %}
        <button type="submit" disabled class="btn-disabled">Add to Cart</button>
        {% else %}
        <button type="submit" value="submit" class="btn">Add to Cart</button>
        {% endif %}
    </form>
    {% else %}
    <a href="{% url 'merchstore:product-edit' product.pk %}" class="btn">Edit Product</a>
    {% endif %}
</div>

{% endblock %}

merchstore/templates/product_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Product List
{% endblock %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'merchstore/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">MERCHSTORE</h1>
<h2 class="error-message">{{ error_message }}</h2>

<div class="user-product">
    <a href="{% url 'merchstore:product-create' %}" class="btn">Create New Product</a>
    <a href="{% url 'merchstore:cart-list' %}" class="btn">View Cart</a>
    <a href="{% url 'merchstore:product-list' %}" class="btn">View Items</a>
    <a href="{% url 'merchstore:transactions' %}" class="btn">View Transactions</a>
</div>

<div class="product-list-wrapper">
<div class="main-content">

    <h2 class="section-title">Your Products</h2>
    {% for product_type in user_product_types %}
    <h3 class="product-type-title">{{ product_type.name }}</h3>

    <div class="product-list">
        {% for product in user_products %}
        {% if product_type == product.product_type %}
        <div class="product-item">
            {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
            {% endif %}
            <div class="product-text">
                <a href="{{ product.get_absolute_url }}" class="product-name">{{ product.name }}</a>
                <div class="product-price">₱{{ product.price }}</div>
                <div class="product-generic">Available Stock: {{ product.stock }}</div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}

   
</div>

<div class="main-content">
     <h2 class="section-title">Products for Sale</h2>
    {% for product_type in other_product_types %}
    <h3 class="product-type-title">{{ product_type.name }}</h3>
    <div class="product-list">
        {% for product in other_products %}
        {% if product_type == product.product_type %}
        <div class="product-item">
            {% if product.image %}
            <img src="{{ product.image.url }}" alt="{{ product.name }}" class="product-image">
            {% endif %}
            <div class="product-text">
                <a href="{{ product.get_absolute_url }}" class="product-name">{{ product.name }}</a>
                <div class="product-price">₱{{ product.price }}</div>
                <div class="product-stock">Available Stock: {{ product.stock }}</div>
            </div>
        </div>
        {% endif %}
        {% endfor %}

    </div>
    {% endfor %}
</div>
</div>

{% endblock %}

merchstore/templates/transaction_list.html
{% extends 'base.html' %}
{% load static %}

{% block title %}
Transactions
{% endblock %}

{% load static %}
{% block head %}
<link rel="stylesheet" href="{% static 'merchstore/styles/style.css' %}">
{% endblock %}

{% block content %}
<h1 class="page-title">MERCHSTORE</h1>
<h2 class="error-message">{{ error_message }}</h2>

<div class="user-product">
    <a href="{% url 'merchstore:cart-list' %}" class="btn">View Cart</a>
    <a href="{% url 'merchstore:product-list' %}" class="btn">View Items</a>
    <a href="{% url 'merchstore:transactions' %}" class="btn">View Transactions</a>
</div>

<div class="main-content">
    <p class="product-generic">Total Value: ₱{{projected_earnings}}</p>
    <h2 class="section-title">Transactions Made as Seller:</h2>

    {% for buyer in buyers %}
    <h3 class="product-type-title">Buyer: {{buyer.display_name}}</h3>
    <div class="product-list">
        {% for item in transactions_sold %}
        {% if item.buyer == buyer %}
        <div class="product-item">
            {% if item.product.image %}
            <img src="{{ item.product.image.url }}" alt="{{ product.name }}" class="product-image">
            {% endif %}
            <div class="product-text">
                <div class="product-name">{{item.product.name}}</div>
                <div class="product-price">₱{{item.product.price}}</div>
                <div class="product-generic">QTY: {{item.amount}}</div>
                <div class="product-generic">{{item.created_on}}</div>
            </div>
        </div>
        {% endif %}
        {% endfor %}
    </div>
    {% endfor %}
</div>

{% endblock %}